# Generated by Django 3.1.5 on 2021-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/c/c2/Fujifilm_X-T100_8_Jun_2018b.jpg', max_length=2000),
        ),
    ]
